# -*- coding: utf-8 -*-
"""Integration tests for the sales lifecycle extension — real Frappe site + DB.

These exercise the engines end-to-end against ERPNext documents (the PRD §11
"golden document" direction): grouped invoicing, rule enforcement, FX snapshot,
posting preview, and config durability.

Because the engine endpoints call ``frappe.db.commit()`` (which defeats the
test-transaction rollback), fixtures are created in ``setUpClass`` and removed
in ``tearDownClass``; every artifact is prefixed ``_ITEST`` for safe cleanup.

Run on bench:
  bench --site <site> set-config allow_tests true
  bench --site <site> run-tests --app trader_app \
        --module trader_app.tests.test_sales_lifecycle_integration

Or standalone against a site:
  cd apps/trader_app && ../../env/bin/python \
        tests/test_sales_lifecycle_integration.py --site <site>
"""

from __future__ import unicode_literals

import unittest

import frappe
from frappe.utils import flt, nowdate

COMPANY = "Electrence"
WAREHOUSE = "Stores - ELECT"
ITEM = "_ITEST Widget"
CUST = "_ITEST Customer A"
CUST2 = "_ITEST Customer B"
RULE = "_ITEST zero-qty blocker"
FXP = "_ITEST fx"
PACK_KEY = "_itest_pack"


def _leaf(doctype):
    rows = frappe.get_all(doctype, filters={"is_group": 0}, pluck="name", limit=1)
    return rows[0] if rows else None


class SalesLifecycleIntegrationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if not frappe.db.exists("Company", COMPANY):
            raise unittest.SkipTest("Company {0} not present on this site".format(COMPANY))
        cls._orig_neg = frappe.db.get_single_value("Stock Settings", "allow_negative_stock")
        frappe.db.set_single_value("Stock Settings", "allow_negative_stock", 1)

        if not frappe.db.exists("Item", ITEM):
            frappe.get_doc({
                "doctype": "Item", "item_code": ITEM, "item_name": ITEM,
                "item_group": _leaf("Item Group"), "stock_uom": "Nos", "is_stock_item": 1,
            }).insert(ignore_permissions=True)
        for name in (CUST, CUST2):
            if not frappe.db.exists("Customer", name):
                frappe.get_doc({
                    "doctype": "Customer", "customer_name": name,
                    "customer_group": _leaf("Customer Group"), "territory": _leaf("Territory"),
                }).insert(ignore_permissions=True)
        frappe.db.commit()

    @classmethod
    def tearDownClass(cls):
        for name in frappe.get_all("Sales Invoice", filters={"customer": ["in", [CUST, CUST2]]}, pluck="name"):
            doc = frappe.get_doc("Sales Invoice", name)
            if doc.docstatus == 1:
                doc.cancel()
            frappe.delete_doc("Sales Invoice", name, ignore_permissions=True, force=True)
        for name in frappe.get_all("Delivery Note", filters={"customer": ["in", [CUST, CUST2]]}, pluck="name"):
            doc = frappe.get_doc("Delivery Note", name)
            if doc.docstatus == 1:
                doc.cancel()
            frappe.delete_doc("Delivery Note", name, ignore_permissions=True, force=True)
        for dt, filt in (
            ("Trader Validation Rule", {"rule_name": RULE}),
            ("Trader FX Policy", {"policy_name": FXP}),
            ("Trader Config Pack", {"company": COMPANY, "pack_key": PACK_KEY}),
        ):
            for name in frappe.get_all(dt, filters=filt, pluck="name"):
                frappe.delete_doc(dt, name, ignore_permissions=True, force=True)
        # decision logs generated by these tests (grouping/validation/fx/posting on our SIs)
        for name in frappe.get_all(
            "Trader Decision Log",
            filters={"reference_name": ["like", "_ITEST%"]}, pluck="name",
        ):
            frappe.delete_doc("Trader Decision Log", name, ignore_permissions=True, force=True)
        for name in (CUST, CUST2):
            if frappe.db.exists("Customer", name):
                frappe.delete_doc("Customer", name, ignore_permissions=True, force=True)
        if frappe.db.exists("Item", ITEM):
            frappe.delete_doc("Item", ITEM, ignore_permissions=True, force=True)
        frappe.db.set_single_value("Stock Settings", "allow_negative_stock", cls._orig_neg or 0)
        frappe.db.commit()

    # ── helpers ─────────────────────────────────────────────────
    def _make_dn(self, customer, qty, rate=100):
        dn = frappe.new_doc("Delivery Note")
        dn.company = COMPANY
        dn.customer = customer
        dn.posting_date = nowdate()
        dn.set_warehouse = WAREHOUSE
        dn.append("items", {"item_code": ITEM, "qty": qty, "rate": rate,
                            "warehouse": WAREHOUSE, "allow_zero_valuation_rate": 1})
        dn.insert(ignore_permissions=True)
        dn.submit()
        return dn.name

    # ── grouped invoicing (FR-7) ────────────────────────────────
    def test_grouped_invoice_merges_challans_and_tracks_consumption(self):
        from trader_app.api.grouped_invoicing import create_grouped_invoice

        dn1 = self._make_dn(CUST, 3)
        dn2 = self._make_dn(CUST, 2)
        res = create_grouped_invoice([dn1, dn2], company=COMPANY, auto_submit=1)

        si = frappe.get_doc("Sales Invoice", res["invoice"])
        self.assertEqual(si.docstatus, 1)
        self.assertEqual(len(si.items), 2)
        self.assertEqual(sum(flt(i.qty) for i in si.items), 5.0)
        self.assertEqual({i.delivery_note for i in si.items}, {dn1, dn2})
        # Native + explicit consumption both reach 100% / full qty.
        self.assertEqual(flt(frappe.db.get_value("Delivery Note", dn1, "per_billed")), 100.0)
        self.assertEqual(
            flt(frappe.db.sql("SELECT SUM(trader_qty_invoiced) FROM `tabDelivery Note Item` WHERE parent=%s", dn1)[0][0]),
            3.0,
        )
        self.assertIn(dn1, res["completed_challans"])

    def test_grouping_rejects_mixed_customers(self):
        from trader_app.api.grouped_invoicing import create_grouped_invoice

        dn_a = self._make_dn(CUST, 1)
        dn_b = self._make_dn(CUST2, 1)
        with self.assertRaises(frappe.ValidationError):
            create_grouped_invoice([dn_a, dn_b], company=COMPANY, auto_submit=0)

    # ── rule engine (FR-4) ──────────────────────────────────────
    def test_validation_rule_blocks_zero_qty_invoice(self):
        from trader_app.api.rules import run_rules

        if not frappe.db.exists("Trader Validation Rule", {"rule_name": RULE}):
            frappe.get_doc({
                "doctype": "Trader Validation Rule", "rule_name": RULE, "company": COMPANY,
                "target_doctype": "Sales Invoice", "event": "validate", "severity": "block",
                "message": "Quantity must be > 0.",
                "condition": {"any": [{"field": "items.qty", "op": "<=", "value": 0}]},
            }).insert(ignore_permissions=True)
            frappe.db.commit()

        bad = frappe.get_doc({"doctype": "Sales Invoice", "company": COMPANY,
                              "customer": CUST, "items": [{"item_code": ITEM, "qty": 0}]})
        with self.assertRaises(frappe.ValidationError):
            run_rules(bad, "validate")

        good = frappe.get_doc({"doctype": "Sales Invoice", "company": COMPANY,
                               "customer": CUST, "items": [{"item_code": ITEM, "qty": 5}]})
        run_rules(good, "validate")  # must not raise

    # ── FX snapshot (FR-6) ──────────────────────────────────────
    def test_fx_snapshot_on_foreign_currency_invoice(self):
        from trader_app.api.fx_policy import snapshot_fx

        if not frappe.db.exists("Trader FX Policy", {"policy_name": FXP}):
            frappe.get_doc({
                "doctype": "Trader FX Policy", "policy_name": FXP, "company": COMPANY,
                "is_active": 1, "snapshot_trigger": "both", "validity_days": 7, "print_mode": "both",
            }).insert(ignore_permissions=True)
            frappe.db.commit()

        usd = frappe.get_doc({"doctype": "Sales Invoice", "company": COMPANY,
                              "currency": "USD", "conversion_rate": 281.0})
        self.assertTrue(snapshot_fx(usd, "finalize"))
        self.assertEqual(flt(usd.trader_fx_rate_snapshot), 281.0)
        self.assertTrue(usd.trader_fx_clause_valid_until)

        pkr = frappe.get_doc({"doctype": "Sales Invoice", "company": COMPANY,
                              "currency": "PKR", "conversion_rate": 1})
        self.assertFalse(snapshot_fx(pkr, "finalize"))  # local currency ignored

    # ── posting dry-run (FR-8) ──────────────────────────────────
    def test_posting_preview_is_balanced_and_nonmutating(self):
        from trader_app.api.posting import preview_posting

        si = frappe.new_doc("Sales Invoice")
        si.company = COMPANY
        si.customer = CUST
        si.posting_date = nowdate()
        si.update_stock = 1
        si.set_warehouse = WAREHOUSE
        si.append("items", {"item_code": ITEM, "qty": 4, "rate": 250,
                            "warehouse": WAREHOUSE, "allow_zero_valuation_rate": 1})
        si.insert(ignore_permissions=True)

        preview = preview_posting("Sales Invoice", si.name)
        self.assertTrue(preview["balanced"])
        self.assertEqual(preview["total_debit"], preview["total_credit"])
        # Dry-run must not submit the document.
        self.assertEqual(frappe.db.get_value("Sales Invoice", si.name, "docstatus"), 0)

    # ── config durability (Phase 0) ─────────────────────────────
    def test_config_pack_survives_cache_flush(self):
        from trader_app.api import config_store

        config_store.write_config(COMPANY, PACK_KEY, {"k": "v", "n": 7}, label="itest")
        frappe.cache().delete_value("trader_config_pack::{0}::{1}".format(COMPANY, PACK_KEY))
        after = config_store.read_config(COMPANY, PACK_KEY, default={})
        self.assertEqual(after.get("k"), "v")
        self.assertEqual(after.get("n"), 7)
        self.assertTrue(frappe.db.exists("Trader Config Pack", {"company": COMPANY, "pack_key": PACK_KEY}))


def _bootstrap_and_run():
    import argparse
    import sys

    parser = argparse.ArgumentParser()
    parser.add_argument("--site", required=True)
    parser.add_argument("--sites-path", default=".")
    args, remaining = parser.parse_known_args()

    frappe.init(site=args.site, sites_path=args.sites_path)
    frappe.connect()
    frappe.set_user("Administrator")
    try:
        suite = unittest.TestLoader().loadTestsFromTestCase(SalesLifecycleIntegrationTests)
        result = unittest.TextTestRunner(verbosity=2).run(suite)
        sys.exit(0 if result.wasSuccessful() else 1)
    finally:
        frappe.destroy()


if __name__ == "__main__":
    _bootstrap_and_run()
